[template]
src = "bucket.conf.tmpl"
dest = "/etc/apache2/haul/nightly.conf"
prefix = "/%%PROJECT%%/%%ENVIRONMENT%%/config/sites/nightly"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/bucket"
]

reload_cmd = "if /etc/init.d/apache2 status ; then /etc/init.d/apache2 reload ; else /etc/init.d/apache2 start; fi"
